# Generated by Django 2.0.3 on 2018-09-17 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ide', '0002_auto_20180918_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='title',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
