# Generated by Django 2.0.3 on 2019-04-13 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ide', '0004_auto_20190413_2040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ide.Problem')),
            ],
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='rating',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='submissions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ide.UserDetail'),
        ),
    ]
