# Generated by Django 2.0.3 on 2019-04-13 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ide', '0005_auto_20190413_2116'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='submissions',
            unique_together={('user', 'problem')},
        ),
    ]
